[tool.poetry]
name = "diive"
version = "0.85.6"
description = "Time series processing"
authors = ["holukas <holukas@ethz.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
pandas = ">=2.1.0"
scipy = ">=1.11.2"
scikit-learn = ">=1.3.0"
matplotlib = ">=3.7.3"
pyyaml = ">=6.0.1"
uncertainties = ">=3.1.7"
statsmodels = ">=0.14.0"
prophet = ">=1.1.4"
seaborn = ">=0.12.2"
bokeh = ">=3.2.2"
pyarrow = ">=13.0.0"
pymannkendall = ">=1.4.3"
yellowbrick = ">=1.5"
shap = ">=0.42.1"
eli5 = ">=0.13.0"
xgboost = ">=2.0.0"
numpy = ">=1.20.0"
dtreeviz = ">=2.2.2"
sktime = ">=0.32.1"
category-encoders = ">=2.6.3"
scikit-optimize = ">=0.10.2"
polars = ">=1.8.1"
jupyterlab = ">=4.2.5"
jupyter-bokeh = ">=4.0.5"

[tool.poetry.group.dev.dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }
#jupyter-bokeh = ">=4.0.5"
#jupyterlab = ">=4.2.5"
sphinx = ">=7.2.6"
sphinxcontrib-napoleon = ">=0.7"
sphinx-rtd-theme = ">=2.0.0"
ipywidgets = ">=8.1.1"
ruff = ">=0.6.8"
autopep8 = ">=2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
