[tool.poetry]
name = "diive"
version = "0.30.0"
description = "Time series post-processing and analysis"
authors = ["holukas <lukas.hoertnagl@usys.ethz.ch>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.3.5"
scipy = "^1.7.3"
PyYAML = "^6.0"
matplotlib = "^3.5.1"
uncertainties = "^3.1.6"
statsmodels = "^0.13.1"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
