[project]
name = "diive"
version = "0.88.0"
description = "Time series processing"
authors = [
    {name = "Lukas Hörtnagl",email = "holukas@ethz.ch"}
]
license = {text = "GNU General Public License v3.0"}
readme = "README.md"
requires-python = ">=3.11,<3.12"
dependencies = [
    "pandas (>=2.2.3,<3.0.0)",
    "xgboost (>=3.0.0,<4.0.0)",
    "scikit-learn (>=1.6.1,<2.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "uncertainties (>=3.2.2,<4.0.0)",
    "statsmodels (>=0.14.4,<0.15.0)",
    "prophet (>=1.1.6,<2.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "bokeh (>=3.7.1,<4.0.0)",
    "pyarrow (>=19.0.1,<20.0.0)",
    "pymannkendall (>=1.4.3,<2.0.0)",
    "yellowbrick (>=1.5,<2.0)",
    "shap (>=0.47.1,<0.48.0)",
    "eli5 (>=0.14.0,<0.15.0)",
    "dtreeviz (>=2.2.2,<3.0.0)",
    "numpy (>=2.2.4,<3.0.0)",
    "sktime (>=0.36.0,<0.37.0)",
    "category-encoders (>=2.8.1,<3.0.0)",
    "scikit-optimize (>=0.10.2,<0.11.0)",
    "polars (>=1.26.0,<2.0.0)",
    "jupyterlab (>=4.3.6,<5.0.0)",
    "jupyter-bokeh (>=4.0.5,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }
ipywidgets = ">=8.1.5"
ruff = ">=0.11.2"
autopep8 = ">=2.3.2"
ghp-import = ">=2.1.0"
jupyter-book = ">=1.0.4.post1"
