[tool.poetry]
name = "diive"
version = "0.52.1"
description = "Time series post-processing and analysis"
authors = ["holukas <lukas.hoertnagl@usys.ethz.ch>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.5.3"
scipy = "^1.10.0"
scikit-learn = "^1.2.0"
matplotlib = "^3.6.3"
PyYAML = "^6.0"
uncertainties = "^3.1.7"
statsmodels = "0.13.1"
pysolar = "^0.10"
ThymeBoost = "^0.1.15"
jupyterlab = "^3.5.2"
prophet = "^1.1.2"
fitter = "^1.5.2"
jupyter-bokeh = "^3.0.5"
seaborn = "^0.12.2"

[tool.poetry.dev-dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
