[tool.poetry]
name = "diive"
version = "0.63.1"
description = "Time series processing"
authors = ["holukas <holukas@ethz.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^2.1.0"
scipy = "^1.11.2"
scikit-learn = "^1.3.0"
matplotlib = "^3.7.3"
pyyaml = "^6.0.1"
uncertainties = "^3.1.7"
statsmodels = "^0.14.0"
pysolar = "^0.11"
thymeboost = "^0.1.16"
prophet = "^1.1.4"
fitter = "^1.6.0"
seaborn = "^0.12.2"
bokeh = "^3.2.2"
pyarrow = "^13.0.0"
pymannkendall = "^1.4.3"
yellowbrick = "^1.5"
shap = "^0.42.1"
eli5 = "^0.13.0"
xgboost = "^2.0.0"

[tool.poetry.dev-dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }
jupyter-bokeh = "^3.0.5"

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.0.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
