[tool.poetry]
name = "diive"
version = "0.41.0"
description = "Time series post-processing and analysis"
authors = ["Lukas Hörtnagl <holukas@ethz.ch>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
pandas = "^1.3.5"
scipy = "^1.7.3"
PyYAML = "^6.0"
matplotlib = "^3.5.1"
uncertainties = "^3.1.6"
statsmodels = "^0.13.1"
Sphinx = "^4.3.2"
sphinx-rtd-theme = "^1.0.0"
pysolar = "^0.10"
scikit-learn = "^1.0.2"
ThymeBoost = "^0.1.10"

[tool.poetry.dev-dependencies]
dbc-influxdb = { path = "../../22 - POET/dbc-influxdb", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
