GENERAL:
  NAME: "DIIVE-CSV-30MIN"
  DESCRIPTION: "Default DIIVE format with 2-row header (variable name, units) and 1-column full timestamp."
  TAGS: [ "DIIVE" ]

FILE:
  EXTENSION: "*.diive.csv"
  COMPRESSION: "None"

TIMESTAMP:
  DESCRIPTION: "1 column with full timestamp with seconds"
  INDEX_COLUMN: [ 0 ]
  DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "middle"

DATA:
  HEADER_SECTION_ROWS: [ 0, 1 ]
  SKIP_ROWS: [ ]
  HEADER_ROWS: [ 0, 1 ]
  VARNAMES_ROW: 0
  VARUNITS_ROW: 1
  NA_VALUES: [ -9999, -6999, -999, "nan", "NaN", "NAN", "NA", "inf", "-inf", "-" ]
  FREQUENCY: "30min"
  DELIMITER: ","
