GENERAL:
  NAME: "EDDYPRO_FULL_OUTPUT_30MIN"
  DESCRIPTION: "The *_full_output_* file from EddyPro."
  TAGS: [ "EDDYPRO" ]

FILE:
  EXTENSION: "*.csv"
  COMPRESSION: "none"

TIMESTAMP:
  DESCRIPTION: "2 columns, date and time in separate columns, time without seconds"
  INDEX_COLUMN: [ [ 'date', '[yyyy-mm-dd]' ], [ 'time', '[HH:MM]' ] ]
  DATETIME_FORMAT: "%Y-%m-%d %H:%M"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "end"

DATA:
  HEADER_SECTION_ROWS: [ 0, 1, 2 ]
  SKIP_ROWS: [ 0 ]
  HEADER_ROWS: [ 0, 1 ]
  NA_VALUES: [ -9999 ]
  FREQUENCY: "30T"
  DELIMITER: ","
