GENERAL:
  NAME: "GENERIC-CSV-HEADER-1ROW-TS-MIDDLE-FULL-NS-30MIN"
  DESCRIPTION: "Generic CSV format with 1-row header containing variable names and 1-column full timestamp with nanoseconds."
  TAGS: [ "GENERIC-CSV" ]

FILE:
  EXTENSION: "*.csv"
  COMPRESSION: "None"

TIMESTAMP:
  DESCRIPTION: "1 column with full timestamp with seconds and nanoseconds"
  INDEX_COLUMN: [ 0 ]
  DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S.%f"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "middle"

DATA:
  HEADER_SECTION_ROWS: [ 0 ]
  SKIP_ROWS: [ ]
  HEADER_ROWS: [ 0 ]
  NA_VALUES: [ -9999, -6999, -999, "nan", "NaN", "NAN", "NA", "inf", "-inf", "-" ]
  FREQUENCY: "50ms"
  DELIMITER: ","
