GENERAL:
  NAME: "ICOS-H2R-CSVZIP-10S"
  DESCRIPTION: "Compressed (zipped) ICOS format with 2-row header (variables, units) and ISO timestamp."
  TAGS: [ "ICOS" ]

FILE:
  EXTENSION: "*.csv"
  COMPRESSION: "zip"

TIMESTAMP:
  DESCRIPTION: "1 column with full ISO timestamp with seconds"
  INDEX_COLUMN: [ 0 ]
  DATETIME_FORMAT: "%Y%m%d%H%M%S"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "end"

DATA:
  HEADER_SECTION_ROWS: [ 0, 1 ]
  SKIP_ROWS: [  ]
  HEADER_ROWS: [ 0, 1 ]
  VARNAMES_ROW: 0
  VARUNITS_ROW: 1
  NA_VALUES: [ -9999, -6999, -999, "nan", "NaN", "NAN", "NA", "inf", "-inf", "-" ]
  FREQUENCY: "10s"
  DELIMITER: ","
