GENERAL:
  NAME: "RECORD-DAT-20HZ"
  DESCRIPTION: "TOA5 format with 4-row header including variable name and units row, and no timestamp."
  TAGS: [ "TOA5" ]

FILE:
  EXTENSION: "*.dat"
  COMPRESSION: "None"

TIMESTAMP:
  DESCRIPTION: "No timestamp in files."
  INDEX_COLUMN: "-not-available-"
  DATETIME_FORMAT: "-not-available-"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "-not-available-"

DATA:
  HEADER_SECTION_ROWS: [ 0, 1, 2, 3 ]
  SKIP_ROWS: [ 0, 3 ]
  HEADER_ROWS: [ 0, 1 ]
  NA_VALUES: [ -9999 ]
  FREQUENCY: "50ms"
  DELIMITER: ","
