GENERAL:
  NAME: "TOA5-DAT-1MIN"
  DESCRIPTION: "TOA5 format with 4-row header including variable name and units row, and 1-column full timestamp."
  TAGS: [ "TOA5" ]

FILE:
  EXTENSION: "*.dat"
  COMPRESSION: "None"

TIMESTAMP:
  DESCRIPTION: "1 column with full timestamp with seconds"
  INDEX_COLUMN: [ 0 ]
  DATETIME_FORMAT: "%Y-%m-%d %H:%M:%S"
  SHOWS_START_MIDDLE_OR_END_OF_RECORD: "end"

DATA:
  HEADER_SECTION_ROWS: [ 0, 1, 2, 3 ]
  SKIP_ROWS: [ 0, 3 ]
  HEADER_ROWS: [ 0, 1 ]
  NA_VALUES: [ -9999 ]
  FREQUENCY: "1T"
  DELIMITER: ","
