# Jupyter Book configuration

title: diive Documentation
author: Lukas Hörtnagl, ETH Grassland Sciences
copyright: "2024"

format: jb-book

execute:
  execute_notebooks: "off"

html:
  use_issues_button: true
  use_repository_button: true
  favicon: null

sphinx:
  config:
    language: en
    html_theme: sphinx_book_theme
