# Jupyter Book Configuration
title: diive Documentation
author: Lukas Hörtnagl
logo: null

# Build settings
format: jb-book
root_doc: intro

# Execution
execute:
  execute_notebooks: "off"

# Output
html:
  use_issues_button: true
  use_repository_button: true
